version: '3'
services:
  jenkins:
    container_name: jenkins
    image: "jenkins/jenkins:lts"
    ports:
    - "8090:8080"
    - "50000:50000"
    volumes:
    - /home/cdd/jenkins_home:/var/jenkins_home
